### ISSUE TITLE
Undefined variable: g:markdown_fenced_languages

### ISSUE THREAD

**Issue by GabMus** [phelipetls/vim-hugo#1]
This error shows up whenever I open a markdown file. I'm using neovim 0.6.0, here's my configuration: https://gitlab.com/gabmus/mydotfiles/-/tree/master/nvim/dot-config/nvim

**Comment by phelipetls** [comment]
Hey, sorry for the long wait on this, I've missed it somehow. I think I solved this, so let me know if you still have any trouble.
